### ISSUE TITLE
Possible bug : matchers not being recognized, but...

### ISSUE THREAD

**Issue by wm-j-ray** [shaps80/Spry#6]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Spry/blob/master/CONTRIBUTING.md) and have done my best to follow them.
I'm pretty sure this is a xCode 9b2 beta bug, but nonetheless..

### What did you do?
Unzipped, and ran the Playground included with the distribution under xCode 9
### What did you expect to happen?
Expected it to run as it does in xCode 8.3
### What actually happened instead?
matchers are unrecognized

Please replace this with what happened instead.

### Environment

List the software versions you're using:

 - Spry: *?.?.?*
Master Branch

 - Xcode Version: *?.? (????)* (Open Xcode; In menubar: Xcode > About Xcode)
9.b2
 - Swift Version: *?.?* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)
None: xCode Default

**Comment by shaps80** [comment]
Thanks for bringing this to my attention, I'll check it out soon.

**Comment by wm-j-ray** [comment]
It could be quick as well. I think they could be having some xCode 9 issues as there is an xCode 9 branch.

**Comment by shaps80** [comment]
After further investigation there is indeed a larger issue. I’ve created a PR for Nimble. Once this is sorted I’ll be able to apply the same fix to Spry.
